version: '2'

services:
  core:
    build: core
    image: andiwand/nagios-core
    container_name: nagios-core
    restart: always
    volumes:
      - nagios-core-link:/usr/local/nagios
      - nagios-config:/usr/local/nagios/etc
      - mail-config:/etc/ssmtp
    environment:
      - NAGIOS_USER_ID=9001
      - NAGCMD_GROUP_ID=9002
  apache:
    build: apache
    image: andiwand/nagios-apache
    container_name: nagios-apache
    restart: always
    ports:
      - "80:80"
    volumes:
      - nagios-core-link:/usr/local/nagios
      - apache-config:/usr/local/nagios/apache
    environment:
      - NAGCMD_GROUP_ID=9002

volumes:
  nagios-core-link:
  nagios-config:
  apache-config:
  mail-config:
